function catalog = case_catalog()
  catalog = struct( ...
    'id', {'ieee14', 'ieee30'}, ...
    'matpowerName', {'case14', 'case_ieee30'}, ...
    'title', {'IEEE 14-bus test system', 'IEEE 30-bus test system'}, ...
    'sourceNote', { ...
      'MATPOWER case14, converted from ieee14cdf.txt of the University of Washington Power Systems Test Case Archive', ...
      'MATPOWER case_ieee30 version 2, converted from ieee30cdf.txt of the University of Washington Power Systems Test Case Archive'});
end
