setup_matpower();
define_constants;
outputDirectory = getenv('OUT_DIR');
catalog = case_catalog();

for entry = catalog
  mpc = load_clean_case(entry.matpowerName);
  baseResult = runpf(mpc, reference_options(false));
  ratings = synthetic_ratings(baseResult);
  ids = branch_ids(mpc.branch);
  layout = schematic_layout(mpc);
  busCount = rows(mpc.bus);

  baseKv = mpc.bus(:, BASE_KV);
  voltageNote = 'base voltages as in the MATPOWER file';
  if strcmp(entry.id, 'ieee14')
    baseKv(:) = 33;
    baseKv(mpc.bus(:, BUS_I) <= 5) = 132;
    voltageNote = 'synthetic base voltages: 132 kV for buses 1 to 5 and 33 kV for buses 6 to 14, the file has none';
  else
    baseKv(mpc.bus(:, BUS_I) == 9) = 33;
    voltageNote = 'base voltages as in the MATPOWER file, except bus 9 set from 1 kV to 33 kV';
  end

  typeNames = {'PQ', 'PV', 'REFERENCE', 'ISOLATED'};
  buses = struct( ...
    'number', num2cell(mpc.bus(:, BUS_I))', ...
    'type', typeNames(mpc.bus(:, BUS_TYPE)), ...
    'baseKv', num2cell(baseKv)', ...
    'vMin', num2cell(mpc.bus(:, VMIN))', ...
    'vMax', num2cell(mpc.bus(:, VMAX))', ...
    'voltageMagnitude', num2cell(mpc.bus(:, VM))', ...
    'voltageAngleDegrees', num2cell(mpc.bus(:, VA))');

  loadRows = find(mpc.bus(:, PD) ~= 0 | mpc.bus(:, QD) ~= 0);
  loads = struct( ...
    'bus', num2cell(mpc.bus(loadRows, BUS_I))', ...
    'pMw', num2cell(mpc.bus(loadRows, PD))', ...
    'qMvar', num2cell(mpc.bus(loadRows, QD))');

  shuntRows = find(mpc.bus(:, GS) ~= 0 | mpc.bus(:, BS) ~= 0);
  shunts = struct( ...
    'bus', num2cell(mpc.bus(shuntRows, BUS_I))', ...
    'gMw', num2cell(mpc.bus(shuntRows, GS))', ...
    'bMvar', num2cell(mpc.bus(shuntRows, BS))');

  generatorIds = cell(1, rows(mpc.gen));
  for k = 1:rows(mpc.gen)
    earlier = sum(mpc.gen(1:k - 1, GEN_BUS) == mpc.gen(k, GEN_BUS));
    generatorIds{k} = sprintf('G%d', mpc.gen(k, GEN_BUS));
    if earlier > 0
      generatorIds{k} = sprintf('G%d-%d', mpc.gen(k, GEN_BUS), earlier + 1);
    end
  end
  generators = struct( ...
    'id', generatorIds, ...
    'bus', num2cell(mpc.gen(:, GEN_BUS))', ...
    'pMw', num2cell(mpc.gen(:, PG))', ...
    'qMvar', num2cell(mpc.gen(:, QG))', ...
    'qMinMvar', num2cell(mpc.gen(:, QMIN))', ...
    'qMaxMvar', num2cell(mpc.gen(:, QMAX))', ...
    'pMinMw', num2cell(mpc.gen(:, PMIN))', ...
    'pMaxMw', num2cell(mpc.gen(:, PMAX))', ...
    'voltageSetpoint', num2cell(mpc.gen(:, VG))', ...
    'inService', num2cell(mpc.gen(:, GEN_STATUS) > 0)');

  tap = mpc.branch(:, TAP);
  tap(tap == 0) = 1;
  branches = struct( ...
    'id', ids, ...
    'from', num2cell(mpc.branch(:, F_BUS))', ...
    'to', num2cell(mpc.branch(:, T_BUS))', ...
    'r', num2cell(mpc.branch(:, BR_R))', ...
    'x', num2cell(mpc.branch(:, BR_X))', ...
    'b', num2cell(mpc.branch(:, BR_B))', ...
    'ratingMva', num2cell(ratings)', ...
    'tap', num2cell(tap)', ...
    'shiftDegrees', num2cell(mpc.branch(:, SHIFT))', ...
    'inService', num2cell(mpc.branch(:, BR_STATUS) > 0)');

  layoutRows = struct( ...
    'bus', num2cell(mpc.bus(:, BUS_I))', ...
    'x', num2cell(layout(:, 1))', ...
    'y', num2cell(layout(:, 2))');

  provenance = provenance_block('export_case.m', entry.sourceNote);
  provenance.ratingPolicy = 'max(ceil(1.25 * peak / 5) * 5, 20) MVA, peak being the larger apparent power at the two ends in the solved base case at 100% load without reactive limits';
  provenance.voltagePolicy = voltageNote;
  provenance.layoutPolicy = 'synthetic schematic coordinates from a deterministic force-directed layout, for drawing only';

  document = struct( ...
    'id', entry.id, ...
    'title', entry.title, ...
    'provenance', provenance, ...
    'baseMva', mpc.baseMVA, ...
    'buses', {num2cell(buses)}, ...
    'loads', {num2cell(loads)}, ...
    'shunts', {num2cell(shunts)}, ...
    'generators', {num2cell(generators)}, ...
    'branches', {num2cell(branches)}, ...
    'layout', {num2cell(layoutRows)});
  write_json(fullfile(outputDirectory, [entry.id '.json']), document);
end
