function block = provenance_block(scriptName, sourceNote)
  block = struct( ...
    'source', sourceNote, ...
    'generatedBy', ['tools/reference/' scriptName], ...
    'matpowerVersion', getenv('MATPOWER_VERSION'), ...
    'matpowerArchiveSha256', getenv('MATPOWER_SHA256'), ...
    'octaveVersion', OCTAVE_VERSION, ...
    'dockerImage', getenv('OCTAVE_IMAGE'), ...
    'powerFlowTolerance', 1e-12, ...
    'powerFlowMaxIterations', 30);
end
