function record = solution_record(mpc, result, ids, meta)
  define_constants;
  buses = struct( ...
    'number', num2cell(result.bus(:, BUS_I))', ...
    'vm', num2cell(result.bus(:, VM))', ...
    'vaDegrees', num2cell(result.bus(:, VA))', ...
    'pdMw', num2cell(mpc.bus(:, PD))', ...
    'qdMvar', num2cell(mpc.bus(:, QD))');
  limitStates = cell(1, rows(result.gen));
  for k = 1:rows(result.gen)
    if abs(result.gen(k, QG) - result.gen(k, QMAX)) < 1e-6
      limitStates{k} = 'UPPER';
    elseif abs(result.gen(k, QG) - result.gen(k, QMIN)) < 1e-6
      limitStates{k} = 'LOWER';
    else
      limitStates{k} = 'NONE';
    end
  end
  generators = struct( ...
    'bus', num2cell(result.gen(:, GEN_BUS))', ...
    'pMw', num2cell(result.gen(:, PG))', ...
    'qMvar', num2cell(result.gen(:, QG))', ...
    'qLimit', limitStates);
  branches = struct( ...
    'id', ids, ...
    'from', num2cell(result.branch(:, F_BUS))', ...
    'to', num2cell(result.branch(:, T_BUS))', ...
    'pFromMw', num2cell(result.branch(:, PF))', ...
    'qFromMvar', num2cell(result.branch(:, QF))', ...
    'pToMw', num2cell(result.branch(:, PT))', ...
    'qToMvar', num2cell(result.branch(:, QT))');
  loss = sum(result.branch(:, PF) + result.branch(:, PT));
  record = struct( ...
    'provenance', meta.provenance, ...
    'case', meta.caseId, ...
    'variant', meta.variant, ...
    'loadFactor', meta.loadFactor, ...
    'enforceQLimits', meta.enforceQLimits, ...
    'converged', logical(result.success), ...
    'iterations', result.iterations, ...
    'baseMva', result.baseMVA, ...
    'totalLoadMw', sum(mpc.bus(:, PD)), ...
    'totalGenerationMw', sum(result.gen(:, PG)), ...
    'totalLossMw', loss, ...
    'buses', {num2cell(buses)}, ...
    'generators', {num2cell(generators)}, ...
    'branches', {num2cell(branches)});
end
